version: '3'

services:
  postgres:
    image: postgres:15.0-alpine
    container_name: postgres152
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  odoo:
    image: odoo:latest
    container_name: odoo17newer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8070:8069"
      - "8072:8072"
    environment:
      HOST: postgres
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./etc/odoo:/etc/odoo
      - ./mnt/extra-addons:/mnt/extra-addons
      - ./data/odoo:/var/lib/odoo

